version: 2

updates:
  - package-ecosystem: "pub"
    directories:
      - "/"
      - "/example"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Singapore"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    allow:
      - dependency-type: "direct"
    labels:
      - "dependencies"
      - "chore"
    groups:
      pub-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Singapore"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    allow:
      - dependency-type: "direct"
    labels:
      - "dependencies"
      - "chore"
    groups:
      actions-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(ci)"
