name: loading_indicator
description: Custom fork of the loading_indicator library
version: 4.0.0
homepage: https://github.com/TinoGuo/loading_indicator

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=3.3.4"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.8.2
  collection: ^1.16.0

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
