name: Flutter Build Test CI

on:
  schedule:
    - cron: '0 8 1/7 * *'
  push:
    branches:
      - master
  pull_request:

jobs:

  matrix_prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      # Required as the JSON input file needs to be read
      - uses: actions/checkout@v3
      - uses: nelonoel/branch-name@v1.0.1
      - id: set-matrix
        uses: JoshuaTheMiller/conditional-build-matrix@main
        with:
          # inputFile: '.github/workflows/matrix_includes.json' # Default input file path
          filter: '[?runOnBranch==`${{ github.ref }}` || runOnBranch==`always`]'
          addInclude: false

  # Set up Flutter for all other tasks.
  setup:
    needs: matrix_prep
    runs-on: ${{ matrix.runs_on }}
    strategy:
      matrix: ${{fromJson(needs.matrix_prep.outputs.matrix)}}
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: ${{ matrix.flutter_path }}
          key: ${{ runner.os }}-flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

  build-and-test:
    needs: setup
    runs-on: ${{ matrix.runs_on }}
    strategy:
      matrix: ${{fromJson(needs.matrix_prep.outputs.matrix)}}
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Cache Flutter
        id: cache-flutter
        uses: actions/cache@v3
        with:
          path: ${{ matrix.flutter_path }}
          key: ${{ runner.os }}-flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: enabled exp platform
        run: |
          flutter config --enable-macos-desktop
      - name: flutter hotbake
        run: |
          flutter pub get
          flutter analyze
          flutter test
      - name: build platform directory
        working-directory: ./example
        run: flutter create .
      # build example
      - name: build android example
        working-directory: ./example
        run: flutter build appbundle
      - if: matrix.os == 'macos-latest'
        name: build ios example
        working-directory: ./example
        run: flutter build ios --release --no-codesign
      - if: matrix.os == 'macos-latest'
        name: build macos example
        working-directory: ./example
        run: flutter build macos
      - name: build web example
        working-directory: ./example
        run: flutter build web
      - if: ${{ matrix.os == 'ubuntu-latest' && github.ref == 'refs/heads/master' }}
        name: deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: example/build/web # The folder the action should deploy.