name: Publish to pub.dev

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions: {}

concurrency:
  group: pub-dev-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pub.dev
    timeout-minutes: 15
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Dart and pub.dev authentication
        uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c # v1.7.1
      - name: Set up Flutter
        uses: flutter-actions/setup-flutter@d4e97a6e7467ef062618c9af927f90bc9651b876
      - name: Install dependencies
        run: dart pub get
      - name: Validate package
        run: dart pub publish --dry-run
      - name: Publish package
        run: dart pub publish --force
